spring.application.name=bug-tracker-lab-juv25g
#auto create entities
spring.jpa.hibernate.ddl-auto=update
#Keep container alive between reboots
spring.docker.compose.lifecycle-management=start_only
#show hibernate
spring.jpa.show-sql=true
